from . import views
from .views import (
    approval_action,
    approval_detail,
    approval_inbox,
    my_requests,
    request_cart,
    request_details,
    collection_inbox,
    collection_detail,
    disburse_request_view,
    collection_history,
    collection_history_detail,
    regenerate_collection_voucher_view,
    open_collection_voucher_view,
    download_collection_voucher_view,
    farmer_reports_view,
    farmer_reports_export_excel_view,
    farmer_report_detail_view,
    farmer_report_detail_export_excel_view,
    farmer_report_detail_export_pdf_view,
    stock_reports_view,
    stock_reports_export_excel_view,
    low_stock_report_view,
    low_stock_report_export_excel_view,
    stock_card_view,
    stock_card_export_excel_view,
    stock_card_export_pdf_view,
    request_tracker_view,
    request_tracker_export_excel_view,
    request_tracker_export_pdf_view,
    exception_reports_view,
    exception_reports_export_excel_view,
    exception_reports_export_pdf_view,
    department_reports_view,
    department_reports_export_excel_view,
    department_report_detail_view,
    department_report_detail_export_excel_view,
    department_report_detail_export_pdf_view,
    department_trends_view,
    department_trends_export_excel_view,
    department_trends_export_pdf_view,
)
from django.urls import path
from .views import (
    approval_action,
    approval_detail,
    approval_inbox,
    my_requests,
    request_cart,
    request_details,
    collection_inbox,
    collection_detail,
    disburse_request_view,
    collection_history,
    collection_history_detail,
    regenerate_collection_voucher_view,
    open_collection_voucher_view,
    download_collection_voucher_view,
    farmer_reports_view,
    farmer_reports_export_excel_view,
    farmer_report_detail_view,
    farmer_report_detail_export_excel_view,
    farmer_report_detail_export_pdf_view,
    stock_reports_view,
    stock_reports_export_excel_view,
    low_stock_report_view,
    low_stock_report_export_excel_view,
    stock_card_view,
    stock_card_export_excel_view,
    stock_card_export_pdf_view,
)

urlpatterns = [
        path("returns/", views.returns_list_view, name="returns_list"),
        path("returns/<str:collection_number>/", views.return_detail_view, name="return_detail"),
        path("requests/<str:request_number>/cancel-remaining/", views.cancel_remaining_balance_view, name="cancel_remaining_balance"),
        path("reports/reversals/", views.reversal_reports_view, name="reversal_reports"),
        path("reports/reversals/export/excel/", views.reversal_reports_export_excel_view, name="reversal_reports_export_excel"),
        path("reports/reversals/export/pdf/", views.reversal_reports_export_pdf_view, name="reversal_reports_export_pdf"),
    path("reports/departments/", department_reports_view, name="department_reports"),
    path("reports/departments/export/excel/", department_reports_export_excel_view, name="department_reports_export_excel"),
    path("reports/departments/<str:department_code>/", department_report_detail_view, name="department_report_detail"),
    path("reports/departments/<str:department_code>/export/excel/", department_report_detail_export_excel_view, name="department_report_detail_export_excel"),
    path("reports/departments/<str:department_code>/export/pdf/", department_report_detail_export_pdf_view, name="department_report_detail_export_pdf"),
    path("reports/departments/trends/", department_trends_view, name="department_trends"),
    path("reports/departments/trends/export/excel/", department_trends_export_excel_view, name="department_trends_export_excel"),
    path("reports/departments/trends/export/pdf/", department_trends_export_pdf_view, name="department_trends_export_pdf"),
        path("reports/request-tracker/", request_tracker_view, name="request_tracker"),
        path("reports/request-tracker/export/excel/", request_tracker_export_excel_view, name="request_tracker_export_excel"),
        path("reports/request-tracker/export/pdf/", request_tracker_export_pdf_view, name="request_tracker_export_pdf"),
        path("reports/exceptions/", exception_reports_view, name="exception_reports"),
        path("reports/exceptions/export/excel/", exception_reports_export_excel_view, name="exception_reports_export_excel"),
        path("reports/exceptions/export/pdf/", exception_reports_export_pdf_view, name="exception_reports_export_pdf"),
    path("reports/stock/", stock_reports_view, name="stock_reports"),
    path("reports/stock/export/excel/", stock_reports_export_excel_view, name="stock_reports_export_excel"),
    path("reports/stock/low-stock/", low_stock_report_view, name="low_stock_report"),
    path("reports/stock/low-stock/export/excel/", low_stock_report_export_excel_view, name="low_stock_report_export_excel"),
    path("reports/stock-card/<str:item_code>/", stock_card_view, name="stock_card"),
    path("reports/stock-card/<str:item_code>/export/excel/", stock_card_export_excel_view, name="stock_card_export_excel"),
    path("reports/stock-card/<str:item_code>/export/pdf/", stock_card_export_pdf_view, name="stock_card_export_pdf"),
    path("reports/farmers/", farmer_reports_view, name="farmer_reports"),
    path("reports/farmers/export/excel/", farmer_reports_export_excel_view, name="farmer_reports_export_excel"),
    path("reports/farmers/<str:grower_number>/", farmer_report_detail_view, name="farmer_report_detail"),
    path("reports/farmers/<str:grower_number>/export/excel/", farmer_report_detail_export_excel_view, name="farmer_report_detail_export_excel"),
    path("reports/farmers/<str:grower_number>/export/pdf/", farmer_report_detail_export_pdf_view, name="farmer_report_detail_export_pdf"),
    path("create/", request_cart, name="request_cart"),
    path("my-requests/", my_requests, name="my_requests"),
    path("my-requests/<str:request_number>/", request_details, name="request_details"),

    path("approvals/", approval_inbox, name="approval_inbox"),
    path("approvals/<str:request_number>/", approval_detail, name="approval_detail"),
    path("approvals/<str:request_number>/action/", approval_action, name="approval_action"),

    # Collection History routes (must be above collections/)


    path("collections/history/", collection_history, name="collection_history"),
    path("collections/history/<str:collection_number>/", collection_history_detail, name="collection_history_detail"),
    path(
        "collections/history/<str:collection_number>/regenerate-voucher/",
        regenerate_collection_voucher_view,
        name="regenerate_collection_voucher",
    ),
    path(
        "collections/history/<str:collection_number>/open-voucher/",
        open_collection_voucher_view,
        name="open_collection_voucher",
    ),
    path(
        "collections/history/<str:collection_number>/download-voucher/",
        download_collection_voucher_view,
        name="download_collection_voucher",
    ),

    path("collections/", collection_inbox, name="collection_inbox"),
    path("collections/<str:request_number>/", collection_detail, name="collection_detail"),
    path("collections/<str:request_number>/disburse/", disburse_request_view, name="disburse_request"),
]
