# Generated by Django 6.0.3 on 2026-03-22 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('departmentid', models.IntegerField(db_column='DepartmentID')),
                ('departmentcode', models.CharField(db_collation='Latin1_General_CI_AS', db_column='DepartmentCode', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Latin1_General_CI_AS', db_column='Name', max_length=255)),
                ('isactive', models.BooleanField(blank=True, db_column='IsActive', null=True)),
                ('authrequired', models.BooleanField(blank=True, db_column='AuthRequired', null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roleid', models.AutoField(db_column='RoleID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Latin1_General_CI_AS', db_column='Name', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Description', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDepartmentRoles',
            fields=[
                ('mapid', models.AutoField(db_column='MapID', primary_key=True, serialize=False)),
                ('departmentname', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='DepartmentName', max_length=255, null=True)),
                ('rolename', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='RoleName', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'User Department Role',
                'verbose_name_plural': 'User Department Roles',
                'db_table': 'UserDepartmentRoles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.IntegerField(db_column='UserID', editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Latin1_General_CI_AS', db_column='Name', max_length=255)),
                ('email', models.CharField(db_collation='Latin1_General_CI_AS', db_column='Email', max_length=255)),
                ('isactive', models.BooleanField(blank=True, db_column='IsActive', null=True)),
                ('passwordhash', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='PasswordHash', max_length=255, null=True)),
                ('salt', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Salt', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'SQL User',
                'verbose_name_plural': 'SQL Users',
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleFeature',
            fields=[
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.roles')),
                ('dashboard', models.BooleanField(default=False)),
                ('create_request', models.BooleanField(default=False)),
                ('my_requests', models.BooleanField(default=False)),
                ('approvals', models.BooleanField(default=False)),
                ('collections', models.BooleanField(default=False)),
                ('reports', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Role Feature Matrix',
                'verbose_name_plural': 'Role Feature Matrices',
                'db_table': 'RoleFeatures',
            },
        ),
    ]
